[ -f /etc/bashrc ] && . /etc/bashrc
alias halo='~ponlars/Public/Halo/halo.sh'
alias sc='wine ~joelro/ProgramFiles/PSC/StarcraftnBW/starCraft.exe'
alias wine='/chalmers/sw/unsup64/wine-1.4.1/bin/wine'
alias warcraft='/chalmers/sw/unsup64/wine-1.4.1/bin/wine /chalmers/users/oskarfr/wc3Frozen\ Throne.exe'
alias dota='wine /chalmers/users/oskarfr/wc3/Errors/DotAlicious\ Gaming\ Client/client.exe'
alias openarena='~joelro/ProgramFiles/openarena/openarena.x86_64'
alias puyo='wine /chalmers/users/oskarfr/Fusion/Fusion364/Fusion.exe'
alias wc3='wine /chalmers/users/oskarfr/wc3/Frozen\ Throne.exe'
alias genesis='wine /chalmers/users/oskarfr/Fusion/Fusion364/Fusion.exe'
alias fusion='wine /chalmers/users/oskarfr/Fusion/Fusion364/Fusion.exe'
alias scbw='wine /chalmers/users/simojoh/bw/StarCraft.exe'
alias chrome='firefox'
