;;;; .emacs -- Emacs config file

;;; Commentary:

;;; Code:

;; start package.el with Emacs
(require 'package)

;; initialize package.el
(package-initialize)

(require 'helm-config)
(global-set-key (kbd "M-x") #'helm-M-x)
(global-set-key (kbd "C-x C-f") #'helm-find-files)
(helm-mode t)

(require 'opencl-mode)
(add-to-list 'auto-mode-alist '("\\.cl\\'" . opencl-mode))

(defun programming-general ()
  "General settings for programming major mode."
  (linum-mode t); Line numbers on
  (flycheck-mode t); on-the-fly syntax checking
  (company-mode t); auto-complete
  (semantic-mode t); semantic
  (global-ede-mode 1)
  (tabbar-mode 1)
  (font-lock-mode 1))

;; TeX
(require 'tex)
(add-hook 'LaTeX-mode-hook
	  (lambda ()
	    (linum-mode t)))
;; Emacs Lisp
(add-hook 'emacs-lisp-mode-hook
	  (lambda ()
	    (programming-general)))
;; c
(add-hook 'c-mode-hook
	  (lambda ()
	    (programming-general)))
;; c++
(add-hook 'c++-mode-hook
	  (lambda ()
	    (programming-general)))
;; java
(add-hook 'java-mode-hook
	  (lambda ()
	    (programming-general)))
;; python
(add-hook 'python-mode-hook
	  (lambda ()
	    (programming-general)
	    (elpy-enable)
	    (pyvenv-workon 'venv)))

;; cython
(add-hook 'cython-mode-hook
	  (lambda ()
	    (programming-general)))

;; emacs autogenerated code
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(blink-cursor-mode nil)
 '(c-initialization-hook nil)
 '(c-mode-common-hook nil)
 '(company-auto-complete t)
 '(company-auto-complete-chars (quote (40 41 34 36 60 62 47)))
 '(company-backends
   (quote
    (company-bbdb company-nxml company-css company-eclim company-semantic company-xcode company-cmake company-capf company-files
		  (company-dabbrev-code company-gtags company-etags company-keywords)
		  company-oddmuse company-dabbrev)))
 '(company-quickhelp-max-lines 50)
 '(company-quickhelp-mode t)
 '(company-quickhelp-use-propertized-text t)
 '(company-tooltip-offset-display (quote scrollbar))
 '(custom-enabled-themes (quote (zenburn)))
 '(custom-safe-themes
   (quote
    ("3f44e2d33b9deb2da947523e2169031d3707eec0426e78c7b8a646ef773a2077" "190a9882bef28d7e944aa610aa68fe1ee34ecea6127239178c7ac848754992df" "e11569fd7e31321a33358ee4b232c2d3cf05caccd90f896e1df6cab228191109" default)))
 '(ecb-auto-activate t)
 '(ecb-major-modes-show-or-hide
   (quote
    ((python-mode c-mode c++-mode java-mode emacs-lisp-mode cython-mode)
     text-mode fundamental-mode Custom-mode Info-mode)))
 '(ecb-options-version "2.50")
 '(ecb-tip-of-the-day nil)
 '(ecb-windows-width 0.25)
 '(elpy-company-post-completion-function (quote elpy-company-post-complete-parens))
 '(elpy-rpc-backend "rope")
 '(global-font-lock-mode t)
 '(package-archives
   (quote
    (("melpa" . "http://melpa.org/packages/")
     ("gnu" . "http://elpa.gnu.org/packages/"))))
 '(package-selected-packages
   (quote
    (cmake-mode flycheck-cython flycheck dumb-jump cython-mode iedit company-c-headers zenburn-theme auctex company-auctex company-quickhelp elpy)))
 '(python-check-command "flake8")
 '(python-shell-completion-native-enable nil)
 '(python-shell-virtualenv-root "/home/marcus/.virtualenvs/venv")
 '(python-skeleton-autoinsert t)
 '(ring-bell-function (quote ignore) t)
 '(semantic-c-dependency-system-include-path (quote ("/usr/include" "/usr/include/gtk-3.0"))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#3F3F3F" :foreground "#DCDCCC" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 143 :width normal :foundry "CTDB" :family "DejaVu-mono"))))
 '(ecb-default-highlight-face ((t (:background "black")))))

(provide (quote .emacs))
;;; .emacs ends here
