;; start package.el with emacs
(require 'package)
;; add MELPA to repository list
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))
;; add marmalade to repository list
(add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))
;; elpy
(add-to-list 'package-archives '("elpy" . "http://jorgenschaefer.github.io/packages/"))
;; initialize package.el
(package-initialize)
;; elpy
(elpy-enable)
;; python virtualenv
(pyvenv-workon 'venv)
;; emacs autogenerated code
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(blink-cursor-mode nil)
 '(company-auto-complete t)
 '(company-backends
   (quote
    (company-jedi company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
		  (company-dabbrev-code company-gtags company-etags company-keywords)
		  company-oddmuse company-dabbrev)))
 '(company-quickhelp-mode t)
 '(company-quickhelp-use-propertized-text t)
 '(company-tooltip-offset-display (quote scrollbar))
 '(custom-enabled-themes (quote (zenburn)))
 '(custom-safe-themes
   (quote
    ("a27c00821ccfd5a78b01e4f35dc056706dd9ede09a8b90c6955ae6a390eb1c1e" "c74e83f8aa4c78a121b52146eadb792c9facc5b1f02c917e3dbb454fca931223" "b9e9ba5aeedcc5ba8be99f1cc9301f6679912910ff92fdf7980929c2fc83ab4d" "84d2f9eeb3f82d619ca4bfffe5f157282f4779732f48a5ac1484d94d5ff5b279" "4e753673a37c71b07e3026be75dc6af3efbac5ce335f3707b7d6a110ecb636a3" default)))
 '(elpy-company-post-completion-function (quote elpy-company-post-complete-parens))
 '(elpy-rpc-backend "jedi")
 '(global-company-mode t)
 '(global-linum-mode t)
 '(inhibit-startup-screen t)
 '(menu-bar-mode nil)
 '(package-selected-packages
   (quote
    (smart-mode-line smart-mode-line-powerline-theme powerline company-c-headers zenburn-theme auctex company-auctex company-quickhelp elpy)))
 '(powerline-default-separator (quote arrow))
 '(powerline-gui-use-vcs-glyph t)
 '(python-check-command "flake8")
 '(python-shell-completion-native-enable nil)
 '(python-shell-virtualenv-root "/home/marcus/.virtualenvs/venv")
 '(python-skeleton-autoinsert t)
 '(scroll-bar-mode nil)
 '(sml/theme (quote powerline))
 '(tool-bar-mode nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#3F3F3F" :foreground "#DCDCCC" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 128 :width normal :foundry "Misc" :family "Fixed"))))
 '(mode-line ((t (:background "#2B2B2B" :foreground "#8FB28F" :box (:line-width -1 :style released-button)))))
 '(mode-line-inactive ((t (:background "#383838" :foreground "gray60" :box (:line-width -1 :style pressed-button) :slant italic))))
 '(powerline-active1 ((t (:inherit mode-line :background "#383838"))))
 '(powerline-inactive1 ((t (:inherit mode-line-inactive :background "#ff00ff"))))
 '(powerline-inactive2 ((t (:inherit mode-line-inactive :background "#00ffff"))))
 '(sml/filename ((t (:inherit sml/global :background "#383838" :foreground "#F0DFAF" :weight bold))))
 '(sml/folder ((t (:inherit (sml/filename sml/global) :background "#383838" :foreground "#F0DFAF" :weight normal))))
 '(sml/git ((t (:inherit (sml/git sml/global) :background "#383838" :foreground "#AFD8AF"))))
 '(sml/global ((t (:inherit mode-line :background "#2B2B2B" :foreground "gray60" :inverse-video nil :weight bold))))
 '(sml/line-number ((t (:inherit mode-line :background "#2B2B2B" :foreground "#F0DFAF" :weight bold))))
 '(sml/modes ((t (:inherit (sml/name-filling sml/global) :background "#5F5F5F" :foreground "#8FB28F" :weight bold))))
 '(sml/modified ((t (:inherit mode-line))))
 '(sml/mule-info ((t (:inherit (mode-line sml/global) :background "#2B2B2B"))))
 '(sml/name-filling ((t (:inherit sml/prefix :background "#5F5F5F" :weight normal))))
 '(sml/not-modified ((t (:inherit mode-line :background "#2B2B2B"))))
 '(sml/position-percentage ((t (:inherit (sml/name-filling sml/prefix) :background "#5F5F5F" :foreground "#330000" :weight normal))))
 '(sml/prefix ((t (:inherit sml/filename :background "#383838" :foreground "#bf6000"))))
 '(sml/process ((t (:inherit sml/prefix :background "#00FF00" :weight bold))))
 '(sml/remote ((t (:inherit (mode-line sml/global) :background "#2B2B2B"))))
 '(sml/sudo ((t (:inherit sml/outside-modified :background "#00ff00" :foreground "#DFAF8F" :weight bold))))
 '(sml/vc ((t (:inherit (sml/name-filling sml/git) :background "#5F5F5F" :foreground "#0000aa")))))

;; smart-mode-line
(sml/setup)
